version : "3.6"

# Sources :
# Minio : https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-compose/docker-compose.yaml
#

networks:
  backend-network:
    name: backend-network
    driver: bridge

volumes:
  data-es:

services:
  minio:
    image: minio/minio:latest
    container_name: backend-minio
    volumes:
     - './data/minio:/data'
    ports:
     - 9200:9000
    environment:
     MINIO_ACCESS_KEY: localTest
     MINIO_SECRET_KEY: pd1d3758d68240e88d5a288e398f1b46
    networks:
      - backend-network
    command: server /data
