namespace Backend.Manager.Helpers.Extension
{
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using Backend.Manager.Helpers.Errors;
    using Backend.Manager.Helpers.Errors.CustomErrors;
    using Microsoft.Extensions.Logging;
    using Newtonsoft.Json;

    /// <summary>
    /// Extension used to define a Fluent method to use for the Error Response Class.
    /// </summary>
    public static class ErrorResponseExtension
    {
        public static ErrorResponse SetError(this ErrorResponse self, bool isError = true)
        {
            self.Error = isError ? 1 : 0;
            return self;
        }

        public static ErrorResponse SetStatusCode(this ErrorResponse self, int statusCode)
        {
            // Set the default value of the Code to Internal Error.
            self.Code = statusCode <= 0 ? 500 : statusCode;
            return self;
        }

        public static ErrorResponse SetUserMessage(this ErrorResponse self, string message)
        {
            self.UserMessage = message;
            return self;
        }

        public static ErrorResponse SetValdidationErrors(this ErrorResponse self, ICollection<ValidationError> values)
        {
            self.ValidationErrors = values.Count == 0 ? null : values;
            return self;
        }

        public static ErrorResponse SetMessage(this ErrorResponse self, string message)
        {
            self.DeveloperMessage.Message = message;
            return self;
        }

        public static ErrorResponse SetMethodName(this ErrorResponse self, string name)
        {
            self.DeveloperMessage.Method = name;
            return self;
        }

        public static ErrorResponse SetInnerException(this ErrorResponse self, string message)
        {
            self.DeveloperMessage.InnerException = string.IsNullOrWhiteSpace(message) ? null : message;
            return self;
        }

        public static ErrorResponse SetStackTrace(this ErrorResponse self, string name)
        {
            self.DeveloperMessage.StackTrace = string.IsNullOrWhiteSpace(name) ? null : name;
            return self;
        }

        public static ErrorResponse SetErrorValues(this ErrorResponse self, object values)
        {
            self.DeveloperMessage.Values = values;
            return self;
        }

        public static ErrorResponse SetDeveloperObject(this ErrorResponse self, DevelopperMessage developperObject)
        {
            self.DeveloperMessage = developperObject;
            return self;
        }

        public static DevelopperMessage GetDeveloperObject(this ErrorResponse self)
        {
            return self.DeveloperMessage;
        }

        /// <summary>
        /// Used to Log the Custom error generated by the Managers actions.
        /// It Create an ApplicationManagerException, log the developer message and return the Error.
        /// </summary>
        /// <param name="logger">{ILogger} The Current manager logger.</param>
        /// <param name="errorType">{ErrorTypes} The Error to throw.</param>
        /// <param name="logObject">{LogObject} The Values of this type are used for tracability.</param>
        /// <param name="methodName">{String} The method that generated this error.</param>
        /// <returns>{ApplicationManagerException} The Custom Manager Error.</returns>
        public static ApplicationManagerException LogAndThrowException(this ILogger logger, ErrorTypes errorType, object logObject, [CallerMemberName] string methodName = null)
        {
            var ex = new ApplicationManagerException(BackendLayersNames.MANAGER, errorType, logObject, methodName: methodName);
            logger.LogError($"{JsonConvert.SerializeObject(ex.ErrorResponse.DeveloperMessage)}");
            return ex;
        }
    }
}
